### ISSUE TITLE
Error on Superslicer

### ISSUE THREAD

**Issue by RedGuilhas** [RomRider/klipper-FastGyroidInfill#1]
I got an error when trying to slice with Superslicer

![image](https://user-images.githubusercontent.com/41800494/145480712-0b330f14-c180-43de-af59-cbdaec41a9f4.png)

Thanks

**Comment by RomRider** [comment]
You'll need to provide the logs from superslicer itself as there's nothing I can use in your screenshot unfortunately.

**Comment by RedGuilhas** [comment]
Sorry. Do you know where the logs are located?

**Comment by Stefkeys** [comment]
Try changing the name of the file Gcode file you are exporting. I think there is an issue with overwriting file names. This fixed an error i was encountering.

I don't know if the is some way the script can be updated to allow overwriting file names.

**Comment by RomRider** [comment]
It should work without any problem while overwriting existing files.

To move forward, what you can do is:
* Disable it from superslicer
* Export your gcode on your disk
* run the script from command line: C:\PATH_TO_PYTHON.EXE C:\PATH_TO_FILE.gcode and report back if there are errors

**Comment by RedGuilhas** [comment]
> It should work without any problem while overwriting existing files.
> 
> To move forward, what you can do is:
> 
> * Disable it from superslicer
> * Export your gcode on your disk
> * run the script from command line: C:\PATH_TO_PYTHON.EXE C:\PATH_TO_FILE.gcode and report back if there are errors

I got this error:
![image](https://user-images.githubusercontent.com/41800494/145861436-c4f942e7-8c68-4975-a8c6-f93428834453.png)

**Comment by RomRider** [comment]
Sorry, my bad, I forgot one piece... it should be C:\PATH_TO_PYTHON.EXE C:\PATH_TO_FastGyroidInfil.py C:\PATH_TO_FILE.gcode

**Comment by RedGuilhas** [comment]
> Sorry, my bad, I forgot one piece... it should be C:\PATH_TO_PYTHON.EXE C:\PATH_TO_FastGyroidInfil.py C:\PATH_TO_FILE.gcode

![image](https://user-images.githubusercontent.com/41800494/145943800-1a7830b1-cdde-4996-8389-5e95923059ac.png)

This is the error I got

**Comment by RomRider** [comment]
You downloaded an HTML file, you need to copy the python file content, not the HTML file.

**Comment by RedGuilhas** [comment]
> You downloaded an HTML file, you need to copy the python file content, not the HTML file.

Sorry,

I got this now

![image](https://user-images.githubusercontent.com/41800494/146222176-6173f97a-d73c-46cd-b7e1-a451226b06c1.png)

**Comment by RomRider** [comment]
You downloaded the cura file, not he SuperSlicer one, please use this one: https://raw.githubusercontent.com/RomRider/klipper-FastGyroidInfill/main/superslicer/FastGyroidInfill.py

**Comment by RedGuilhas** [comment]
> You downloaded the cura file, not he SuperSlicer one, please use this one: https://raw.githubusercontent.com/RomRider/klipper-FastGyroidInfill/main/superslicer/FastGyroidInfill.py

Done. Thank you.
You can close this issue.
