### ISSUE TITLE
Unable to overwrite previously exported Gcode of the same name with SuperSlicer

### ISSUE THREAD

**Issue by Stefkeys** [RomRider/klipper-FastGyroidInfill#3]
Unable to export Gcode file if I have already exported a previously sliced file of the same name. I believe this is due to the .sqv.bak file that is saved along with the Gcode file. If I delete the previous .sqv.bak I am then able to export with the post processing script.

Post-processing script C:\Python310\python.exe C:\Users\acste\Documents\FastGyroidInfill.py on file C:\Users\acste\Desktop\3D printing\GCode\Eevee_Switch_Stand.gcode failed.
Error code: 1

Running script in CMD

> Traceback (most recent call last):
>   File "C:\Users\acste\Documents\FastGyroidInfill.py", line 16, in <module>
>     os.rename(sourceFile, destFile+".sqv.bak")
> WindowsError: [Error 183] Cannot create a file when that file already exists
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\acste\Documents\FastGyroidInfill.py", line 17, in <module>
>     except FileExistsError:
> NameError: name 'FileExistsError' is not defined

**Comment by RomRider** [comment]
Seems like you're using python2 and not python3 as `NameError: name 'FileExistsError' is not defined` is typical of python2.

**Comment by Stefkeys** [comment]
> Seems like you're using python2 and not python3 as `NameError: name 'FileExistsError' is not defined` is typical of python2.

I definitely had Python 3 installed. But I went ahead and removed all Python instances and reinstalled 3.10.1

now I get this error

> C:\Users\acste>C:\Users\acste\AppData\Local\Programs\Python\Python310\python.exe C:\Users\acste\Documents\FastGyroidInfill.py on file C:\Users\acste\Desktop\3D_printing\GCode\Eevee_Switch_Stand.gcode
> Traceback (most recent call last):
>   File "C:\Users\acste\Documents\FastGyroidInfill.py", line 10, in <module>
>     with open(sourceFile, "r") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'on'
>

**Comment by RomRider** [comment]
remove `on file` from your command line ;)
`C:\Users\acste\AppData\Local\Programs\Python\Python310\python.exe C:\Users\acste\Documents\FastGyroidInfill.py C:\Users\acste\Desktop\3D_printing\GCode\Eevee_Switch_Stand.gcode`

**Comment by Stefkeys** [comment]
> remove `on file` from your command line ;) `C:\Users\acste\AppData\Local\Programs\Python\Python310\python.exe C:\Users\acste\Documents\FastGyroidInfill.py C:\Users\acste\Desktop\3D_printing\GCode\Eevee_Switch_Stand.gcode`

Gosh darn it! I was scouring those lines to find "on" and my eyes failed me miserably!

It works! 
Closing issue
